# config.yml of the Basix plugin created by GreatGodApollo.
# MineCraft color codes can be used by using an `&` followed by the color code, ie: &c

motd:
  enabled: true
  msg: '&4Please set this message using /motd set'

# In this case [player] is replaced with the player's display name
suicide:
  msg: '&4[player] took the easy way out!'
